feat: 004/005.md: try emoji prefix in CLI and JetBrains
approvers/site-data pull request #8
Opened 2021-01-30 15:30 UTC by loxygenK

さすがに投げ過ぎな気がするのでこれ投げたらしばらく引っ込みます()

2021-01-30 15:38 UTC, siketyan requested changes
全体的に Emoji Prefix と Emoji prefix で統一されていません．また今回は Gitmoji を紹介されていますが Gitmoji の README にとくに Emoji [Pp]refix の記述がなかったのでこの言葉のソースがほしいです．固有名詞でないのであれば「絵文字コミット」くらいの日本語にしたほうがいいかもしれません．あと Gitmoji に scope 書いてるのあまりみたことないかも．

2021-01-30 15:38 UTC, siketyan commented on data/blogs/004.md
> +**普段CLIで作業している変態向け**記事です。**[JetBrains製エディタユーザの方はこちらをご覧ください](/blog/005)** :pray:
```suggestion
**普段CLIで作業している変態向け**記事です。**[JetBrains製IDEユーザの方はこちらをご覧ください](/blog/005)** :pray:
```

2021-01-30 15:38 UTC, siketyan commented on data/blogs/004.md
> +Emoji prefixというのは **コミットメッセージ** の形式の一つです。
```suggestion
Emoji Prefixというのは **コミットメッセージ** の形式の一つです。
```

2021-01-30 15:38 UTC, siketyan commented on data/blogs/004.md
> +Emoji prefixでない形式であれば…
```suggestion
Emoji Prefixでない形式であれば…
```

2021-01-30 15:38 UTC, siketyan commented on data/blogs/004.md
> +というような書き方が主流です。他にも
```suggestion
というような書き方 (Conventional Commits) が主流です。他にも
```

2021-01-30 15:38 UTC, siketyan commented on data/blogs/004.md
> +fix(READMDE.md): fix typo in the example
```suggestion
fix(README.md): fix typo in the example
```

2021-01-30 15:38 UTC, siketyan commented on data/blogs/004.md
> +では、Emoji prefixがどうかというと…
```suggestion
では、Emoji Prefixがどうかというと…
```

2021-01-30 15:38 UTC, siketyan commented on data/blogs/004.md
> +Emoji prefixにはルールが存在していて、それに沿ったコミットをすることで、**ひと目で変更の概略をつかめるようになります**。加えて、
```suggestion
Emoji Prefixにはルールが存在していて、それに沿ったコミットをすることで、**ひと目で変更の概略をつかめるようになります**。加えて、
```

2021-01-30 15:38 UTC, siketyan commented on data/blogs/004.md
> +✏️(README.md) fix typo in the example
Gitmoji ならこっちのはずです
```suggestion
📝(README.md) fix typo in the example
```

2021-01-30 15:38 UTC, siketyan commented on data/blogs/004.md
> +Enterを押すといつものコミットメッセージ入力画面に**Emoji prefixされたコミットメッセージ**が入力されている画面になります。
```suggestion
Enterを押すといつものコミットメッセージ入力画面に**Emoji Prefixされたコミットメッセージ**が入力されている画面になります。
```

2021-01-30 15:42 UTC, siketyan requested changes
続き

2021-01-30 15:42 UTC, siketyan commented on data/blogs/005.md
> +**普段JetBrainsエディタで作業している方向け**記事です。[CLIで暮らしている方はこちらをご覧ください](/blog/004) :pray:
```suggestion
**普段JetBrains IDEで作業している方向け**記事です。[CLIで暮らしている方はこちらをご覧ください](/blog/004) :pray:
```

2021-01-30 15:42 UTC, siketyan commented on data/blogs/005.md
> +Emoji prefixというのは **コミットメッセージ** の形式の一つです。
```suggestion
Emoji Prefixというのは **コミットメッセージ** の形式の一つです。
```

2021-01-30 15:42 UTC, siketyan commented on data/blogs/005.md
> +Emoji prefixでない形式であれば…
```suggestion
Emoji Prefixでない形式であれば…
```

2021-01-30 15:42 UTC, siketyan commented on data/blogs/005.md
> +✏️(README.md) fix typo in the example
```suggestion
📝(README.md) fix typo in the example
```

2021-01-30 15:42 UTC, siketyan commented on data/blogs/005.md
> +他の形式で `feat` や `fix` など、いわゆる **"Prefix"に英単語を用いる**のに対して、Emoji prefixでは :sparkles: や :pencil2:、:bug:などの **絵文字を使用します**。かわいすぎ。
```suggestion
他の形式で `feat` や `fix` など、いわゆる **"Prefix"に英単語を用いる**のに対して、Emoji Prefixでは :sparkles: や :pencil2:、:bug:などの **絵文字を使用します**。かわいすぎ。
```

2021-01-30 15:42 UTC, siketyan commented on data/blogs/005.md
> +- **インストールしたいJetBrains製エディタで設定画面に行き、プラグインを検索しインストールする**
```suggestion
- **インストールしたいJetBrains製IDEで設定画面に行き、プラグインを検索しインストールする**
```

2021-01-30 17:05 UTC, loxygenK commented
R/Cに対応しました、よろしくおねがいします :pray:

2021-01-30 17:22 UTC, MikuroXina requested changes

2021-01-30 17:22 UTC, MikuroXina commented on data/blogs/004.md
> +このコマンドを実行すると、上に記したコミットのウィザードが実行でいます。ただし、ウィザードが完了したあと **コミットメッセージの編集画面を介さずにコミットされる** ので注意です。[^1]
```suggestion
このコマンドを実行すると、上に記したコミットのウィザードが実行できます。ただし、ウィザードが完了したあと **コミットメッセージの編集画面を介さずにコミットされる** ので注意です。[^1]
```

2021-01-30 17:22 UTC, MikuroXina commented on data/blogs/004.md
> +[^1]: 加えて、`git add`し忘れたまま`gitmoji -ci`すると、コミットメッセージの確定時に例外を吐いて堕ちます。フック張っておくのが確実?
(意図したものなら Resolve しておいてね)
```suggestion
[^1]: 加えて、`git add`し忘れたまま`gitmoji -ci`すると、コミットメッセージの確定時に例外を吐いて落ちます。フック張っておくのが確実?
```

2021-01-30 17:22 UTC, MikuroXina commented on data/blogs/005.md
> +![](https://i.imgur.com/4hxWWCQ.png)
画像に `alt` を書いておいてください (他の画像も同様).

2021-01-30 17:22 UTC, MikuroXina commented on data/blogs/005.md
> +- GitToolBoxを入れて設定すればめんどくさくない
```suggestion
- Gitmoji Plus: Commit Buttonを入れて設定すればめんどくさくない
```

2021-01-30 17:35 UTC, loxygenK commented on data/blogs/005.md
> +![](https://i.imgur.com/4hxWWCQ.png)
b319ae5 / 773cff9 :bow:

2021-01-30 17:37 UTC, MikuroXina approved these changes

2021-01-30 17:41 UTC, siketyan requested changes
今更なんですけど gitmoji-cli を使うかプラグインを使うかのとこ以外同じすぎて分散が起こってるのでセクション分けぐらいでいいんじゃないかなと思っています．あと img の代替テキストは対象を日本語話者にするなら日本語であるべき

2021-01-30 17:41 UTC, siketyan commented on data/blogs/004.md
> +今回は、 **絵文字を使用する形式** のコミットメッセージの書き方をご紹介します。<br />
```suggestion
今回は、 **絵文字を使用する形式** のコミットメッセージの書き方をご紹介します。<br>
```

2021-01-30 17:41 UTC, siketyan commented on data/blogs/004.md
> +他の形式で `feat` や `fix` など、いわゆる **"Prefix"に英単語を用いる**のに対して、絵文字コミットでは :sparkles: や :pencil2:、:bug:などの **絵文字を使用します**。かわいすぎ。
```suggestion
他の形式で `feat` や `fix` など、いわゆる **"接頭辞"に英単語を用いる**のに対して、絵文字コミットでは :sparkles: や :pencil2:、:bug:などの **絵文字を使用します**。かわいすぎ。
```

2021-01-30 17:41 UTC, siketyan commented on data/blogs/004.md
> +- **GPG(PGP)を用いたSignedコミットの強制**
```suggestion
- **GPG(PGP)を用いた署名付きコミットの強制**
```

2021-01-30 17:41 UTC, siketyan commented on data/blogs/005.md
> +今回は、 **絵文字を使用する形式** のコミットメッセージの書き方をご紹介します。<br />
```suggestion
今回は、 **絵文字を使用する形式** のコミットメッセージの書き方をご紹介します。<br>
```

2021-01-31 00:47 UTC, loxygenK commented
R/C に対応しました :pray:
リンクがちゃんとレンダリングされていませんがTypora経由でPDF出力してテストしてみたら大丈夫だったので一応リンクは貼られているはずです :bow:

2021-01-31 00:52 UTC, siketyan approved these changes

2021-01-31 03:59 UTC, merged