fix: prevented emoji expansion and adjusted outline level
approvers/site-data pull request #9
Opened 2021-01-31 04:41 UTC by loxygenK

以下のことをしました:
- 意図していないemoji-tagの展開を防いだ。
- 002〜004.md のアウトラインのレベル(というのかわからない)を1つ下げた。
  - 記事タイトルと「`#`」が同じ`h1`だったため。

2021-02-01 16:22 UTC, MikuroXina requested changes
見出しレベルに関しては問題ありません (サイト側の記事タイトル部を改修する PR を作成した) ので, emoji-tag 部分の修正だけにしてほしいです.

2021-02-06 00:53 UTC, loxygenK commented
720dc4a で修正しました :pray: ( revert するコミットを間違えてしまい revert が3つ生えてしまいました )

2021-02-06 04:34 UTC, MikuroXina commented on data/blogs/004.md
> +🗑  - : wastebasket : - Deprecate code that needs to be cleaned up.
ここだけスペースが一つ増えてますけど, 意図してますか?
```suggestion
🗑 - : wastebasket : - Deprecate code that needs to be cleaned up.
```

2021-02-06 04:36 UTC, loxygenK commented on data/blogs/004.md
> +🗑  - : wastebasket : - Deprecate code that needs to be cleaned up.
意図してませんでした、ありがとうございます :bow:
4f4fa87 で修正しました。

2021-02-06 04:37 UTC, MikuroXina approved these changes

2021-02-06 04:39 UTC, merged